version: "3.8"
   
services:
    django:
        build: .
        working_dir: /usr/src/app/ripper_site
        container_name: django
        command: pdm run python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
        depends_on:
            # - pgdb
            - redis
    celery:
        build: .
        working_dir: /usr/src/app/ripper_site
        command: pdm run celery -A ripper_site worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
        depends_on:
            - django
            - redis 
    redis:
        image: "redis:alpine"